name: Docker Image CI

on:
  push:
    branches: 'main'

jobs:
  push_to_registery:
    name: Push img to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          token: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push img
        uses: docker/build-push-action@v4
        with: 
          context: DockerFile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/nbx:latest
