name: Docker Image CI

on:
  push:
    branches: '*'

jobs:
  push_to_registery:
    name: Push img to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build img
        uses: docker/build-push-action@v4
        with: 
          push: false 

      - name: Push img to Docker Hub
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/nbx:latest
